usethis::use_package("here")
usethis::use_package("dplyr")
usethis::use_package("attempt")
usethis::use_package("cli")
usethis::use_package("ggplot2")
usethis::use_package("magrittr")
usethis::use_package("purrr")
usethis::use_package("RcppRoll")
usethis::use_package("stats")
usethis::use_package("stringr")
usethis::use_package("janitor")
usethis::use_package("utils")
usethis::use_package("readxl")
usethis::use_package("scales")
usethis::use_package("sf")
usethis::use_package("tidyr")
usethis::use_package("usethis")
usethis::use_package("lubridate")
usethis::use_data(df_codelgt, overwrite = TRUE)
usethis::use_rmarkdown_template(template_name = "plaquette_drplus",
                                template_description = "Script qui va transformer le tableau en entree en plaquette")
usethis::use_data(df_moislib, overwrite = TRUE)
usethis::use_data(map_regwkt, overwrite = TRUE)
usethis::use_package("tibble")
usethis::use_package("COGiter")
usethis::use_data(df_palettecouleur, overwrite = TRUE)
usethis::use_version(which = "minor")
usethis::use_package("rvest")
usethis::use_package("xml2")
usethis::use_package("utf8")
usethis::use_version(which = "minor")
usethis::use_version(which = "minor")
usethis::use_git()
usethis::use_readme_rmd()
usethis::use_lifecycle_badge("experimental")
usethis::use_version(which = "minor")
usethis::use_version(which = "minor")
usethis::use_version(which = "minor")
