usethis::use_package("here")
usethis::use_package("dplyr")
usethis::use_package("attempt")
usethis::use_package("cli")
usethis::use_package("ggplot2")
# usethis::use_package("magrittr")
usethis::use_package("purrr")
usethis::use_package("RcppRoll")
usethis::use_package("stats")
usethis::use_package("stringr")
usethis::use_package("janitor")
usethis::use_package("utils")
usethis::use_package("readxl")
usethis::use_package("scales")
usethis::use_package("sf")
usethis::use_package("tidyr")
usethis::use_package("usethis")
usethis::use_package("lubridate")
usethis::use_data(df_codelgt, overwrite = TRUE)
usethis::use_rmarkdown_template(template_name = "plaquette_drplus",
                                template_description = "Script qui va transformer le tableau en entree en plaquette")
usethis::use_data(df_moislib, overwrite = TRUE)
usethis::use_data(map_regwkt, overwrite = TRUE)
usethis::use_package("tibble")
usethis::use_package("COGiter")
usethis::use_data(df_palettecouleur, overwrite = TRUE)
usethis::use_version(which = "minor")
usethis::use_package("rvest")
usethis::use_package("xml2")
usethis::use_package("utf8")
usethis::use_version(which = "minor")
usethis::use_version(which = "minor")
usethis::use_git()
usethis::use_readme_rmd()
usethis::use_lifecycle_badge("experimental")
usethis::use_version(which = "minor")
usethis::use_version(which = "minor")
usethis::use_version(which = "minor")
usethis::use_vignette("Utiliser_sitascribe2")
usethis::use_r("fn07_graphe_lgt_type_evol_area")
usethis::use_r("fn11_evol1an_type_lgt_bonus1")
usethis::use_r("fn11_evol1an_type_lgt_bonus2")
usethis::use_package("DT")
usethis::use_r("fn00_verifie_existe_modele")
usethis::use_package("plotly")
usethis::use_package("writexl")
usethis::use_r("fn_scri_ls_nodes_tableau")
usethis::use_r("fn_scri_ls_nodes_cellules_tableau")
usethis::use_r("fn_scri_modifie_tableau")
usethis::use_version(which = "minor")
usethis::use_vignette("Les_images")
